version: "3"
services:
  bpcrs-db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'bpcrs'
      MYSQL_ROOT_PASSWORD: '1qaz2wsx'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - /mysqldata:/var/lib/mysql
    restart: on-failure
    network_mode: host
  bpcrs-backend:
    image: docker.pkg.github.com/bpcrs/back-end/bpcrs-backend:latest
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 5000:5000
    network_mode: host