version: "3"
services:
  bpcrs-db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'bpcrs'
      MYSQL_ROOT_PASSWORD: '1qaz2wsx'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: on-failure
    networks:
      - bpcrs
  bpcrs-backend:
    image: docker.pkg.github.com/bpcrs/back-end/bpcrs-backend:latest
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 5000:5000
    networks:
      - bpcrs
  dapp-nest:
    image: docker.pkg.github.com/bpcrs/dapp-nest/dapp-nest:latest
    volumes:
    - ./bpcrs-network/crypto-config:/app/dist/crypto-config
    - ./wallet:/app/dist/wallet
    network_mode: host
networks:
  bpcrs:
    driver: bridge