spring:
  datasource:
    username: root
    password: 1qaz2wsx
    url: jdbc:mysql://bpcrs-db:3306/bpcrs
app:
  host: api.bpcrs.network

dapp:
  pem:
    file: crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
  ca:
    url: localhost:7054
  network:
    config:
      path: crypto-config/peerOrganizations/org1.example.com/connection-org1.yaml
